In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")


# Feature Engineering

In [2]:
df = pd.read_excel('diabetes.xlsx')
df

Age  Gender Polyuria Polydipsia Sudden_weight_loss weakness Polyphagia  \
0     40    Male       No        Yes                 No      Yes         No   
1     58    Male       No         No                 No      Yes         No   
2     41    Male      Yes         No                 No      Yes        Yes   
3     45    Male       No         No                Yes      Yes        Yes   
4     60    Male      Yes        Yes                Yes      Yes        Yes   
..   ...     ...      ...        ...                ...      ...        ...   
515   39  Female      Yes        Yes                Yes       No        Yes   
516   48  Female      Yes        Yes                Yes      Yes        Yes   
517   58  Female      Yes        Yes                Yes      Yes        Yes   
518   32  Female       No         No                 No      Yes         No   
519   42    Male       No         No                 No       No         No   

    Genital_thrush Visual_blurring Itching Irritability delayed_healing  \
0               No              No     Yes           No             Yes   
1               No             Yes      No           No              No   
2               No              No     Yes           No             Yes   
3              Yes              No     Yes           No             Yes   
4               No             Yes     Yes          Yes             Yes   
..             ...             ...     ...          ...             ...   
515             No              No     Yes           No             Yes   
516             No              No     Yes          Yes             Yes   
517             No             Yes      No           No              No   
518             No             Yes     Yes           No             Yes   
519             No              No      No           No              No   

    partial_paresis muscle_stiffness Alopecia Obesity     Class  
0                No              Yes      Yes     Yes  Positive  
1               Yes               No      Yes      No  Positive  
2                No              Yes      Yes      No  Positive  
3                No               No       No      No  Positive  
4               Yes              Yes      Yes     Yes  Positive  
..              ...              ...      ...     ...       ...  
515             Yes               No       No      No  Positive  
516             Yes               No       No      No  Positive  
517             Yes              Yes       No     Yes  Positive  
518              No               No      Yes      No  Negative  
519              No               No       No      No  Negative  

[520 rows x 17 columns]

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 520 entries, 0 to 519
Data columns (total 17 columns):
 #   Column              Non-Null Count  Dtype 
---  ------              --------------  ----- 
 0   Age                 520 non-null    int64 
 1   Gender              520 non-null    object
 2   Polyuria            520 non-null    object
 3   Polydipsia          520 non-null    object
 4   Sudden_weight_loss  520 non-null    object
 5   weakness            520 non-null    object
 6   Polyphagia          520 non-null    object
 7   Genital_thrush      520 non-null    object
 8   Visual_blurring     520 non-null    object
 9   Itching             520 non-null    object
 10  Irritability        520 non-null    object
 11  delayed_healing     520 non-null    object
 12  partial_paresis     520 non-null    object
 13  muscle_stiffness    520 non-null    object
 14  Alopecia            520 non-null    object
 15  Obesity             520 non-null    object
 16  Class               520 no

# Handling missing value 

In [4]:
df.isnull().sum()

Age                   0
Gender                0
Polyuria              0
Polydipsia            0
Sudden_weight_loss    0
weakness              0
Polyphagia            0
Genital_thrush        0
Visual_blurring       0
Itching               0
Irritability          0
delayed_healing       0
partial_paresis       0
muscle_stiffness      0
Alopecia              0
Obesity               0
Class                 0
dtype: int64

# Data Visualization

#Bivariate Analysis 

In [5]:
df.describe()

Age
count  520.000000
mean    48.028846
std     12.151466
min     16.000000
25%     39.000000
50%     47.500000
75%     57.000000
max     90.000000

# Feature Transformation

# LabelEncoder

In [6]:
df['Gender'] = df['Gender'].map({'Male':1,'Female':0})
df['Class'] = df['Class'].map({'Positive':1,'Negative':0})

In [7]:
from sklearn.preprocessing import LabelEncoder

In [8]:
df1=df.copy()

In [9]:
for x in df.columns:
    if  x != 'Gender' and x != 'Class' and x != 'Age':
        df[x] = LabelEncoder().fit_transform(df[x])

In [10]:
df

Age  Gender  Polyuria  Polydipsia  Sudden_weight_loss  weakness  \
0     40       1         0           1                   0         1   
1     58       1         0           0                   0         1   
2     41       1         1           0                   0         1   
3     45       1         0           0                   1         1   
4     60       1         1           1                   1         1   
..   ...     ...       ...         ...                 ...       ...   
515   39       0         1           1                   1         0   
516   48       0         1           1                   1         1   
517   58       0         1           1                   1         1   
518   32       0         0           0                   0         1   
519   42       1         0           0                   0         0   

     Polyphagia  Genital_thrush  Visual_blurring  Itching  Irritability  \
0             0               0                0        1             0   
1             0               0                1        0             0   
2             1               0                0        1             0   
3             1               1                0        1             0   
4             1               0                1        1             1   
..          ...             ...              ...      ...           ...   
515           1               0                0        1             0   
516           1               0                0        1             1   
517           1               0                1        0             0   
518           0               0                1        1             0   
519           0               0                0        0             0   

     delayed_healing  partial_paresis  muscle_stiffness  Alopecia  Obesity  \
0                  1                0                 1         1        1   
1                  0                1                 0         1        0   
2                  1                0                 1         1        0   
3                  1                0                 0         0        0   
4                  1                1                 1         1        1   
..               ...              ...               ...       ...      ...   
515                1                1                 0         0        0   
516                1                1                 0         0        0   
517                0                1                 1         0        1   
518                1                0                 0         1        0   
519                0                0                 0         0        0   

     Class  
0        1  
1        1  
2        1  
3        1  
4        1  
..     ...  
515      1  
516      1  
517      1  
518      0  
519      0  

[520 rows x 17 columns]

In [11]:
x_idep = df.drop('Class',axis=1)
x_idep

Age  Gender  Polyuria  Polydipsia  Sudden_weight_loss  weakness  \
0     40       1         0           1                   0         1   
1     58       1         0           0                   0         1   
2     41       1         1           0                   0         1   
3     45       1         0           0                   1         1   
4     60       1         1           1                   1         1   
..   ...     ...       ...         ...                 ...       ...   
515   39       0         1           1                   1         0   
516   48       0         1           1                   1         1   
517   58       0         1           1                   1         1   
518   32       0         0           0                   0         1   
519   42       1         0           0                   0         0   

     Polyphagia  Genital_thrush  Visual_blurring  Itching  Irritability  \
0             0               0                0        1             0   
1             0               0                1        0             0   
2             1               0                0        1             0   
3             1               1                0        1             0   
4             1               0                1        1             1   
..          ...             ...              ...      ...           ...   
515           1               0                0        1             0   
516           1               0                0        1             1   
517           1               0                1        0             0   
518           0               0                1        1             0   
519           0               0                0        0             0   

     delayed_healing  partial_paresis  muscle_stiffness  Alopecia  Obesity  
0                  1                0                 1         1        1  
1                  0                1                 0         1        0  
2                  1                0                 1         1        0  
3                  1                0                 0         0        0  
4                  1                1                 1         1        1  
..               ...              ...               ...       ...      ...  
515                1                1                 0         0        0  
516                1                1                 0         0        0  
517                0                1                 1         0        1  
518                1                0                 0         1        0  
519                0                0                 0         0        0  

[520 rows x 16 columns]

In [12]:
y_dep=df['Class']
y_dep

0      1
1      1
2      1
3      1
4      1
      ..
515    1
516    1
517    1
518    0
519    0
Name: Class, Length: 520, dtype: int64

# Feature Importance

# Information gain - mutual information In Classification

In [13]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x_idep,y_dep,
    test_size=0.2,
    random_state=0)

In [14]:
from sklearn.feature_selection import chi2
f_p_values=chi2(x_train,y_train)

In [15]:
f_p_values

(array([2.16525699e+01, 2.93051158e+01, 9.36433498e+01, 9.39940541e+01,
        4.51953216e+01, 1.06889004e+01, 2.84783069e+01, 2.50434783e+00,
        1.47560847e+01, 9.11250000e-02, 2.46410526e+01, 2.10526316e-01,
        5.12382022e+01, 3.43311258e+00, 2.06428571e+01, 2.35294118e+00]),
 array([3.26771909e-06, 6.18322348e-08, 3.77821401e-22, 3.16473107e-22,
        1.78330586e-11, 1.07780250e-03, 9.47542198e-08, 1.13532476e-01,
        1.22352048e-04, 7.62751793e-01, 6.90646644e-07, 6.46355196e-01,
        8.18109345e-13, 6.39015609e-02, 5.53432710e-06, 1.25046880e-01]))

In [16]:
p_values=pd.Series(f_p_values[1])
p_values.index=x_train.columns
p_values


Age                   3.267719e-06
Gender                6.183223e-08
Polyuria              3.778214e-22
Polydipsia            3.164731e-22
Sudden_weight_loss    1.783306e-11
weakness              1.077802e-03
Polyphagia            9.475422e-08
Genital_thrush        1.135325e-01
Visual_blurring       1.223520e-04
Itching               7.627518e-01
Irritability          6.906466e-07
delayed_healing       6.463552e-01
partial_paresis       8.181093e-13
muscle_stiffness      6.390156e-02
Alopecia              5.534327e-06
Obesity               1.250469e-01
dtype: float64

In [17]:
p_values.sort_index(ascending=False)

weakness              1.077802e-03
partial_paresis       8.181093e-13
muscle_stiffness      6.390156e-02
delayed_healing       6.463552e-01
Visual_blurring       1.223520e-04
Sudden_weight_loss    1.783306e-11
Polyuria              3.778214e-22
Polyphagia            9.475422e-08
Polydipsia            3.164731e-22
Obesity               1.250469e-01
Itching               7.627518e-01
Irritability          6.906466e-07
Genital_thrush        1.135325e-01
Gender                6.183223e-08
Alopecia              5.534327e-06
Age                   3.267719e-06
dtype: float64

In [18]:
# # As we found in mutual_info_classification the fields are considered for analysis, 
# # so we drop only (Diabetes, Visited_Public_Exposed_Places, Gastrointestinal, Chronic_Lung_Disease, Heart_Disease)
# # which has no relationship with dependent variable or very less with this data set alone
# df=df.drop('Gastrointestinal ', axis=1)
# df=df.drop('Sanitization_from_Market', axis=1)

In [19]:
# x_idep=x_idep.drop('Gastrointestinal ', axis=1)
# x_idep=x_idep.drop('Sanitization_from_Market', axis=1)

-------

In [20]:
from sklearn.model_selection import train_test_split

In [21]:
xtrain,xtest,ytrain,ytest=train_test_split(x_idep,y_dep,test_size=0.2,random_state=20)

In [22]:
# pip install imblearn

In [23]:
import imblearn

In [24]:
x_idep

Age  Gender  Polyuria  Polydipsia  Sudden_weight_loss  weakness  \
0     40       1         0           1                   0         1   
1     58       1         0           0                   0         1   
2     41       1         1           0                   0         1   
3     45       1         0           0                   1         1   
4     60       1         1           1                   1         1   
..   ...     ...       ...         ...                 ...       ...   
515   39       0         1           1                   1         0   
516   48       0         1           1                   1         1   
517   58       0         1           1                   1         1   
518   32       0         0           0                   0         1   
519   42       1         0           0                   0         0   

     Polyphagia  Genital_thrush  Visual_blurring  Itching  Irritability  \
0             0               0                0        1             0   
1             0               0                1        0             0   
2             1               0                0        1             0   
3             1               1                0        1             0   
4             1               0                1        1             1   
..          ...             ...              ...      ...           ...   
515           1               0                0        1             0   
516           1               0                0        1             1   
517           1               0                1        0             0   
518           0               0                1        1             0   
519           0               0                0        0             0   

     delayed_healing  partial_paresis  muscle_stiffness  Alopecia  Obesity  
0                  1                0                 1         1        1  
1                  0                1                 0         1        0  
2                  1                0                 1         1        0  
3                  1                0                 0         0        0  
4                  1                1                 1         1        1  
..               ...              ...               ...       ...      ...  
515                1                1                 0         0        0  
516                1                1                 0         0        0  
517                0                1                 1         0        1  
518                1                0                 0         1        0  
519                0                0                 0         0        0  

[520 rows x 16 columns]

In [25]:
y_dep

0      1
1      1
2      1
3      1
4      1
      ..
515    1
516    1
517    1
518    0
519    0
Name: Class, Length: 520, dtype: int64

In [26]:
from collections import Counter

In [27]:
counter=Counter(y_dep)
counter

Counter({1: 320, 0: 200})

In [28]:
y_dep.value_counts()

1    320
0    200
Name: Class, dtype: int64

In [29]:
from imblearn.over_sampling import SMOTE
bal=SMOTE()

In [30]:
x_idep, y_dep= bal.fit_resample(x_idep, y_dep)

In [31]:
y_dep.value_counts()

1    320
0    320
Name: Class, dtype: int64

-----

# Logistic Regression

In [32]:
from sklearn.model_selection import train_test_split

In [33]:
xtrain,xtest,ytrain,ytest = train_test_split(x_idep,y_dep, test_size=0.2)

In [34]:
from sklearn.linear_model import LogisticRegression

In [35]:
model=LogisticRegression()
modelfit = model.fit(xtrain,ytrain)

In [36]:
from sklearn.metrics import classification_report,accuracy_score,confusion_matrix

In [37]:
Predict_model0=modelfit.predict(xtest)

In [38]:
confusion_matrix(ytest,Predict_model0)

array([[59,  4],
       [ 5, 60]])

In [39]:
lr_acc=(accuracy_score(ytest,Predict_model0)*100,"%")
lr_acc

(92.96875, '%')

In [40]:
# classification report

In [41]:
import sklearn
from sklearn.metrics import classification_report 

In [42]:
classification_reports=print(classification_report(ytest,Predict_model0))

              precision    recall  f1-score   support

           0       0.92      0.94      0.93        63
           1       0.94      0.92      0.93        65

    accuracy                           0.93       128
   macro avg       0.93      0.93      0.93       128
weighted avg       0.93      0.93      0.93       128



----

# SVM Classifier

In [43]:
from sklearn.svm import SVC

In [44]:
sv=SVC

In [45]:
model=SVC(C=1000, gamma= 0.01, kernel="rbf")

In [46]:
fit_model= model.fit(xtrain,ytrain)

In [47]:
fit_model.n_support_

array([38, 46], dtype=int32)

In [48]:
Predict_model3 = fit_model.predict(xtest)

In [49]:
confusion_matrix(ytest,Predict_model3)

array([[60,  3],
       [ 3, 62]])

In [50]:
svc_acc=(accuracy_score(ytest,Predict_model3)*100,"%")
svc_acc

(95.3125, '%')

In [51]:
classification_reports=print(classification_report(ytest,Predict_model3))

              precision    recall  f1-score   support

           0       0.95      0.95      0.95        63
           1       0.95      0.95      0.95        65

    accuracy                           0.95       128
   macro avg       0.95      0.95      0.95       128
weighted avg       0.95      0.95      0.95       128



# Gradient Boosting Classifier

In [52]:
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.model_selection import GridSearchCV, cross_val_score
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier

In [53]:
from sklearn import preprocessing

In [54]:
from sklearn.ensemble import GradientBoostingClassifier

In [55]:
from sklearn.model_selection import GridSearchCV, train_test_split

In [56]:
# Initiate the best model
model_GB = GradientBoostingClassifier(max_depth=4, min_samples_split=7)

In [57]:
# Fit the best model
model_GB_fit=model_GB.fit(xtrain, ytrain)

In [58]:
Predict_model1 = model_GB_fit.predict(xtest)

In [59]:
confusion_matrix(ytest,Predict_model1)

array([[62,  1],
       [ 2, 63]])

In [60]:
gbm_acc=(accuracy_score(ytest,Predict_model1)*100,"%")
gbm_acc

(97.65625, '%')

In [61]:
classification_reports=print(classification_report(ytest,Predict_model1))

              precision    recall  f1-score   support

           0       0.97      0.98      0.98        63
           1       0.98      0.97      0.98        65

    accuracy                           0.98       128
   macro avg       0.98      0.98      0.98       128
weighted avg       0.98      0.98      0.98       128



______

# Random Forest Classifier

In [62]:
from sklearn.ensemble import RandomForestClassifier

In [63]:
# Initiate the best model
rf_best_model = RandomForestClassifier()

In [64]:
# Fit the best model
Random_model=rf_best_model.fit(xtrain, ytrain)

In [65]:
Predict_model2 = Random_model.predict(xtest)

In [66]:
confusion_matrix(ytest,Predict_model2)

array([[63,  0],
       [ 0, 65]])

In [67]:
rf_acc=(accuracy_score(ytest,Predict_model2)*100,"%")
rf_acc

(100.0, '%')

In [68]:
classification_reports=print(classification_report(ytest,Predict_model2))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        63
           1       1.00      1.00      1.00        65

    accuracy                           1.00       128
   macro avg       1.00      1.00      1.00       128
weighted avg       1.00      1.00      1.00       128



_________

# Gradio

In [69]:
import gradio as gd

In [70]:
df['Gender'].unique()

array([1, 0])

In [71]:
df.head()

Age  Gender  Polyuria  Polydipsia  Sudden_weight_loss  weakness  \
0   40       1         0           1                   0         1   
1   58       1         0           0                   0         1   
2   41       1         1           0                   0         1   
3   45       1         0           0                   1         1   
4   60       1         1           1                   1         1   

   Polyphagia  Genital_thrush  Visual_blurring  Itching  Irritability  \
0           0               0                0        1             0   
1           0               0                1        0             0   
2           1               0                0        1             0   
3           1               1                0        1             0   
4           1               0                1        1             1   

   delayed_healing  partial_paresis  muscle_stiffness  Alopecia  Obesity  \
0                1                0                 1         1        1   
1                0                1                 0         1        0   
2                1                0                 1         1        0   
3                1                0                 0         0        0   
4                1                1                 1         1        1   

   Class  
0      1  
1      1  
2      1  
3      1  
4      1

In [72]:
Age = gd.inputs.Dropdown([16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,
                          43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,
                          71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90],label='Age')

In [73]:
Gender = gd.inputs.Dropdown(['Male', 'Female'],label='Gender')

In [74]:
Polyuria = gd.inputs.Dropdown(['Yes', 'No'],label='Polyuria')

In [75]:
Polydipsia = gd.inputs.Dropdown(['Yes', 'No'],label='Polydipsia')

In [76]:
Sudden_weight_loss = gd.inputs.Dropdown(['Yes', 'No'],label= 'Sudden_weight_loss')

In [77]:
weakness = gd.inputs.Dropdown(['Yes', 'No'],label= 'weakness')

In [78]:
Polyphagia = gd.inputs.Dropdown(['Yes', 'No'],label= 'Polyphagia')

In [79]:
Genital_thrush = gd.inputs.Dropdown(['Yes', 'No'],label= 'Genital_thrush')

In [80]:
Visual_blurring = gd.inputs.Dropdown(['Yes', 'No'],label= 'Visual_blurring')

In [81]:
Itching = gd.inputs.Dropdown(['Yes', 'No'],label= 'Itching')

In [82]:
Irritability = gd.inputs.Dropdown(['Yes', 'No'],label= 'Irritability')

In [83]:
delayed_healing  = gd.inputs.Dropdown(['Yes', 'No'],label= 'delayed_healing ')

In [84]:
partial_paresis = gd.inputs.Dropdown(['Yes', 'No'],label= 'partial_paresis')

In [85]:
muscle_stiffness = gd.inputs.Dropdown(['Yes', 'No'],label= 'muscle_stiffness')

In [86]:
Alopecia = gd.inputs.Dropdown(['Yes', 'No'],label= 'Alopecia')

In [87]:
Obesity = gd.inputs.Dropdown(['Yes', 'No'],label= 'Obesity')

In [88]:
df.columns

Index(['Age', 'Gender', 'Polyuria', 'Polydipsia', 'Sudden_weight_loss',
       'weakness', 'Polyphagia', 'Genital_thrush', 'Visual_blurring',
       'Itching', 'Irritability', 'delayed_healing', 'partial_paresis',
       'muscle_stiffness', 'Alopecia', 'Obesity', 'Class'],
      dtype='object')

In [89]:
def mod(Age,Gender,Polyuria,Polydipsia,Sudden_weight_loss,weakness,Polyphagia,Genital_thrush,Visual_blurring,
        Itching,Irritability,delayed_healing,partial_paresis,muscle_stiffness,Alopecia,Obesity):
    x1 = [Age,Gender,Polyuria,Polydipsia,Sudden_weight_loss,weakness,Polyphagia,Genital_thrush,Visual_blurring,
        Itching,Irritability,delayed_healing,partial_paresis,muscle_stiffness,Alopecia,Obesity]
    test=pd.read_excel('diabetes.xlsx')
    test=test.drop(['Class'],axis=1)
    x1 =pd.DataFrame(np.array(x1).reshape(1,-1),columns=test.columns)
    test = test.append(x1,ignore_index = True)
#     test['Gender'] = test['Gender'].map({'Male':1,'Female':0})
#     test['Class'] = test['Class'].map({'Positive':1,'Negative':0})
    for x in test.columns:
        if  x != 'Class' and x != 'Age':
            test[x] = LabelEncoder().fit_transform(test[x])
    x2 = test.iloc[-1,:]
    y_hat =  Random_model.predict(np.array(x2).reshape(1,-1))
    pred={0:"Negative", 1:"Positive"}
    return pred[y_hat[0]]

In [90]:
gd.Interface(mod, [Age,Gender,Polyuria,Polydipsia,Sudden_weight_loss,weakness,Polyphagia,Genital_thrush,Visual_blurring,
        Itching,Irritability,delayed_healing,partial_paresis,muscle_stiffness,Alopecia,Obesity],
             gd.outputs.Textbox(label='Diabetes')).launch()


Running locally at: http://127.0.0.1:7860/
To create a public link, set `share=True` in `launch()`.
Interface loading below...


(<Flask 'gradio.networking'>, 'http://127.0.0.1:7860/', None)

---------

# Conclusion

In [91]:
L_R = {'Accuracy':lr_acc}
S_V_C = {'Accuracy':svc_acc}
G_B_M = {'Accuracy':gbm_acc}
R_f  = {'Accuracy':rf_acc}


In [92]:
DataFrame = pd.DataFrame(data=[L_R,S_V_C,G_B_M,R_f],index=["Logistic Regression","Support Vector Machine Classifier",
                                                           "Gradient Boosting Classifier","Random forest Classifier "])

DataFrame

Accuracy
Logistic Regression                (92.96875, %)
Support Vector Machine Classifier   (95.3125, %)
Gradient Boosting Classifier       (97.65625, %)
Random forest Classifier              (100.0, %)

------